import { ArrowLeft, BarChart3, BrainCircuit, BriefcaseBusiness, LogOut, Plus, Users } from 'lucide-react'
import { useEffect, useState } from 'react'
import api from '../services/api'

function RecruiterDashboard({ onLogout }) {
  const [jobs, setJobs] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  useEffect(() => { api.get('/recruiter/jobs').then((response) => setJobs(response.data.jobs)).catch((requestError) => setError(requestError.response?.data?.error || 'Unable to load jobs.')).finally(() => setLoading(false)) }, [])
  function logout() { localStorage.removeItem('smart-campus-token'); localStorage.removeItem('smart-campus-user'); onLogout() }
  return <main className="min-h-screen bg-ink px-6 py-6 text-white lg:px-10"><header className="mx-auto flex max-w-7xl items-center justify-between border-b border-white/10 pb-6"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-lime text-ink"><BrainCircuit size={21} /></span><span className="font-display font-bold">Smart Campus</span></div><button className="button-secondary gap-2 px-3 py-2" onClick={logout}><LogOut size={15} /> Log out</button></header><section className="mx-auto max-w-7xl py-12"><div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Recruiter workspace</p><h1 className="mt-4 font-display text-4xl font-bold">Shape your candidate shortlist.</h1><p className="mt-4 leading-7 text-white/55">Post focused roles and let the matching model surface eligible student talent.</p></div><a className="button-primary gap-2 px-5 py-3" href="/recruiter/post-job"><Plus size={17} /> Post a job</a></div><div className="mt-10 grid gap-4 sm:grid-cols-3"><Metric icon={<BriefcaseBusiness size={18} />} label="Jobs posted" value={jobs.length} /><Metric icon={<Users size={18} />} label="Total applicants" value={jobs.reduce((total, job) => total + job.applicant_count, 0)} /><Metric icon={<BarChart3 size={18} />} label="Ranking model" value="70 / 30" /></div>{error && <p className="mt-8 rounded-lg border border-red-400/20 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</p>}{loading ? <p className="mt-10 text-white/50">Loading your jobs...</p> : <div className="mt-10 overflow-hidden rounded-2xl border border-white/10 bg-panel"><div className="border-b border-white/10 px-6 py-5"><h2 className="font-display text-xl font-bold">Your jobs</h2></div>{jobs.length === 0 ? <p className="p-10 text-white/45">No jobs posted yet.</p> : <div className="divide-y divide-white/10">{jobs.map((job) => <div className="flex flex-col justify-between gap-4 px-6 py-5 sm:flex-row sm:items-center" key={job.id}><div><h3 className="font-display font-semibold">{job.job_title}</h3><p className="mt-1 text-sm text-white/45">{job.company} · {job.location} · {job.applicant_count} applicants</p></div><a className="button-secondary gap-2 px-4 py-2" href={`/recruiter/jobs/${job.id}/candidates`}>Rank candidates <ArrowLeft className="rotate-180" size={15} /></a></div>)}</div>}</div>}</section></main>
}
function Metric({ icon, label, value }) { return <div className="rounded-2xl border border-white/10 bg-panel p-5"><span className="text-lime">{icon}</span><p className="mt-5 text-sm text-white/45">{label}</p><p className="mt-1 font-display text-2xl font-bold">{value}</p></div> }
export default RecruiterDashboard
